# Generated by Django 4.2.9 on 2024-01-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
