# Generated by Django 4.2.9 on 2024-01-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_project_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="handle",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
