# Generated by Django 4.2.9 on 2024-01-11 19:35

from django.db import migrations, models
import projects.validators


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_project_added_by_project_added_by_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="handle",
            field=models.SlugField(
                blank=True,
                null=True,
                unique=True,
                validators=[projects.validators.validate_project_handle],
            ),
        ),
    ]
